import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const photosDir = path.join(__dirname, '../public/photos');
const outputFile = path.join(__dirname, '../src/photos.js');

const IMAGE_EXTENSIONS = new Set(['.jpg', '.jpeg', '.webp', '.png', '.heic', '.heif']);

function toId(filename) {
  return filename
    .replace(/\.[^.]+$/i, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function collectPhotos(dir) {
  if (!fs.existsSync(dir)) return [];

  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
    .filter((name) => !name.startsWith('.'))
    .filter((name) => IMAGE_EXTENSIONS.has(path.extname(name).toLowerCase()))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }))
    .map((filename) => {
      const id = toId(filename) || 'photo';
      return { id, filename };
    });
}

const photos = collectPhotos(photosDir);

const entries = photos
  .map(
    ({ id, filename }) => `  {
    id: '${id}',
    src: \`\${base}photos/${filename}\`,
  }`,
  )
  .join(',\n');

const content = `// Auto-generated by scripts/sync-photos.mjs — do not edit by hand.
// Drop images into public/photos/ and run: npm run sync-photos
// Metadata is read from EXIF/IPTC/XMP on load. Optional overrides can be added manually after sync.
const base = import.meta.env.BASE_URL;

export const photos = [
${entries}
];
`;

fs.writeFileSync(outputFile, content);
console.log(`Synced ${photos.length} photo(s) to src/photos.js`);
