import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const photosDir = path.join(__dirname, '../public/photos');
const outputFile = path.join(__dirname, '../src/photos.js');

const IMAGE_EXTENSIONS = new Set(['.jpg', '.jpeg', '.webp', '.png', '.heic', '.heif']);

function toId(filename) {
  return filename
    .replace(/\.[^.]+$/i, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function readExistingSettings() {
  if (!fs.existsSync(outputFile)) return {};

  const content = fs.readFileSync(outputFile, 'utf8');
  const settings = {};

  for (const match of content.matchAll(
    /id:\s*'([^']+)'[\s\S]*?downloadable:\s*(true|false)/g,
  )) {
    settings[match[1]] = { downloadable: match[2] === 'true' };
  }

  return settings;
}

function collectPhotos(dir) {
  if (!fs.existsSync(dir)) return [];

  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
    .filter((name) => !name.startsWith('.'))
    .filter((name) => IMAGE_EXTENSIONS.has(path.extname(name).toLowerCase()))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }))
    .map((filename) => {
      const id = toId(filename) || 'photo';
      return { id, filename };
    });
}

const existingSettings = readExistingSettings();
const photos = collectPhotos(photosDir);

const entries = photos
  .map(({ id, filename }) => {
    const downloadable = existingSettings[id]?.downloadable ?? true;
    return `  {
    id: '${id}',
    src: \`\${base}photos/${filename}\`,
    downloadable: ${downloadable},
  }`;
  })
  .join(',\n');

const content = `// Auto-generated by scripts/sync-photos.mjs — do not edit by hand.
// Drop images into public/photos/ and run: npm run sync-photos
// Set downloadable: false on any photo to hide the download button in the lightbox.
// Metadata is read from EXIF/IPTC/XMP on load. Other optional overrides can be added manually after sync.
const base = import.meta.env.BASE_URL;

export const photos = [
${entries}
];
`;

fs.writeFileSync(outputFile, content);
console.log(`Synced ${photos.length} photo(s) to src/photos.js`);
