// Auto-generated by scripts/sync-photos.mjs — do not edit by hand.
// Drop images into public/photos/ and run: npm run sync-photos
// Set downloadable: false on any photo to hide the download button in the lightbox.
// Metadata is read from EXIF/IPTC/XMP on load. Other optional overrides can be added manually after sync.
const base = import.meta.env.BASE_URL;

export const photos = [
  {
    id: 'beach',
    src: `${base}photos/Beach.jpg`,
    downloadable: true,
  },
  {
    id: 'brake',
    src: `${base}photos/Brake.jpg`,
    downloadable: true,
  },
  {
    id: 'church',
    src: `${base}photos/Church.jpg`,
    downloadable: true,
  },
  {
    id: 'classic',
    src: `${base}photos/classic.jpg`,
    downloadable: true,
  },
  {
    id: 'disc',
    src: `${base}photos/Disc.jpg`,
    downloadable: true,
  },
  {
    id: 'hair',
    src: `${base}photos/Hair.jpg`,
    downloadable: false,
  },
  {
    id: 'horse',
    src: `${base}photos/Horse.jpg`,
    downloadable: true,
  },
  {
    id: 'neon',
    src: `${base}photos/Neon.jpg`,
    downloadable: false,
  },
  {
    id: 'steering',
    src: `${base}photos/Steering.jpg`,
    downloadable: true,
  },
  {
    id: 'swan',
    src: `${base}photos/Swan.jpg`,
    downloadable: true,
  }
];
